### ISSUE TITLE
Compare ps for diffuse model runs

### ISSUE THREAD

**Issue by bhazelton** [nicholebarry/MWA_data_analysis#3]
See if ps is substantially worse for polarized diffuse based run.

**Comment by nicholebarry** [comment]
Looks like expected: power pushed from window to wedge due to calibration changes, model changes due to polarization fixes (xx->yy). No real evidence that this is an issue in the diffuse maps.
![fhd__apb_std_dec2014c_golden_minus_rlb_devel_nodiffuse_june2015_aug23_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11130330/528e1e98-8939-11e5-8c24-93b4024ab894.png)
