### ISSUE TITLE
Run single snapshot firstpass with maximal calibration parameters

### ISSUE THREAD

**Issue by bhazelton** [nicholebarry/MWA_data_analysis#7]
aka 'overfit' and compare with your favorite calibration strategy. Might be interesting to look at this comparison with real data as well as simulation.

**Comment by nicholebarry** [comment]
Looks pretty sweet. Here is a maximal calibration parameters minus a saved cable from longrun data (minimal calibration parameters as of now), using real data + eor. In retrospect, I should have left of the eor signal, since the eor signal should be present in real data, so I'm essentially doubling the eor signal.
![fhd_nb_realdata_cal_beamperchannel_eor__overfit_obs_id_6176_minus_savedcable_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11188817/a8710c02-8c41-11e5-849f-496e346477d3.png)
I also have an enhanced eor version (1000x) to simulate integrating down significantly. This was run in the past to try to see signal loss.
![fhd_nb_realdata_cal_beamperchannel_eor_enhance__overfit_obs_id_6176_minus_savedcable_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11188908/04ea7946-8c42-11e5-8173-c8cac46e1ff2.png)

**Comment by nicholebarry** [comment]
Also, for fun, is the real data simulation of cable calibration for one obsid minus cable calibration averaged over the season 1 data.
![fhd_nb_realdata_cal_beamperchannel_eor__cable_obs_id_6176_minus_savedcable_obs_id_6176_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/5588290/11190881/0979987e-8c4d-11e5-91b8-665b4cb6eeec.png)
